<a href="https://colab.research.google.com/github/IndraMadika/ML-Mentoring/blob/main/Logistic%20Regression%20pd%20Iris%20dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Load dataset

In [1]:
from sklearn.datasets import load_iris
dataset = load_iris()

In [2]:
dataset

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [35]:
import pandas as pd
import numpy as np
df = pd.DataFrame(data['data'], columns=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])
df['target'] = data['target']

print(df)

     sepal_length  sepal_width  petal_length  petal_width  target
0             5.1          3.5           1.4          0.2       0
1             4.9          3.0           1.4          0.2       0
2             4.7          3.2           1.3          0.2       0
3             4.6          3.1           1.5          0.2       0
4             5.0          3.6           1.4          0.2       0
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3       2
146           6.3          2.5           5.0          1.9       2
147           6.5          3.0           5.2          2.0       2
148           6.2          3.4           5.4          2.3       2
149           5.9          3.0           5.1          1.8       2

[150 rows x 5 columns]


In [14]:
print(dataset['data'].shape)
print('rows :',dataset['target_names'])

(150, 4)
rows : ['setosa' 'versicolor' 'virginica']


Standarize the data

In [15]:
from sklearn.preprocessing import StandardScaler as scaler

In [20]:
dataset['data'] = scaler().fit_transform(dataset['data'])
print(dataset['data'])
print(dataset['target'])

[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e

In [18]:
print(dataset['data'].shape)

(150, 4)


In [19]:
print(dataset['target'].shape)
print('rows :',dataset['target_names'])

(150,)
rows : ['setosa' 'versicolor' 'virginica']


Split dataset

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, x_test, Y_train, y_test = train_test_split(dataset['data'],dataset['target'],train_size = 0.8,test_size = 0.2)

Use Logistic Regression

In [8]:
from sklearn.linear_model import LogisticRegression

In [9]:
LR = LogisticRegression()

In [22]:
LR.fit(X_train,Y_train)

In [29]:
LR.score(x_test,y_test)

0.9333333333333333

In [31]:
y_pred = LR.predict(x_test)

In [34]:
# Mendapatkan daftar nama label
label_names = dataset['target_names']

# Menampilkan nama label hasil prediksi
for idx in y_pred:
    label = label_names[idx]
    print(idx,label)

1 versicolor
1 versicolor
1 versicolor
2 virginica
1 versicolor
2 virginica
0 setosa
1 versicolor
1 versicolor
0 setosa
1 versicolor
1 versicolor
2 virginica
2 virginica
1 versicolor
1 versicolor
1 versicolor
2 virginica
2 virginica
0 setosa
2 virginica
0 setosa
0 setosa
0 setosa
2 virginica
1 versicolor
0 setosa
2 virginica
0 setosa
2 virginica
